### ISSUE TITLE
default config is missing from pip package

### ISSUE THREAD

**Issue by veonua** [iejMac/video2dataset#250]
video2dataset --url_list="videos.csv" --url_col="url" --output_folder="video2output"
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/evobits/miniconda3/bin/video2dataset", line 5, in <module>
    from video2dataset.main import main
  File "/home/evobits/miniconda3/lib/python3.11/site-packages/video2dataset/__init__.py", line 3, in <module>
    from .main import video2dataset
  File "/home/evobits/miniconda3/lib/python3.11/site-packages/video2dataset/main.py", line 30, in <module>
    from .configs import CONFIGS
  File "/home/evobits/miniconda3/lib/python3.11/site-packages/video2dataset/configs/__init__.py", line 8, in <module>
    "default": OmegaConf.load(os.path.join(configs_path, "default.yaml")),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evobits/miniconda3/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/evobits/miniconda3/lib/python3.11/site-packages/video2dataset/configs/default.yaml'

**Comment by linhan0109** [comment]
I also encountered this problem, have you solved it?

**Comment by veonua** [comment]
I manually copied all the yamls from GitHub

**Comment by pableeto** [comment]
The error still persists with pip install as in 1/16/2024.

**Comment by rom1504** [comment]
@pableeto could you please try again now? I made a new release
